// host-vue/src/pages/dashboard/Connector.vue
<template>
  <div>
    <div id="dashboardModule"></div>
  </div>
</template>

<script>
  import { mount } from "dashboardModule/DashboardProvider";
  export default {
    data() {
      return {
        iswatch: true,
      };
    },
    mounted() {
      this.initialPath = this.$route.matched[0].path;

      const {onParentNavigate, onUnmount} = mount(document.getElementById("dashboardModule"), {
        baseUrl: '/dashboard',
        initialPath: this.initialPath,
        onNavigate: ({pathname: nextPathname}) => {
          const pathname = this.$route.path;

          if (pathname !== nextPathname) {
            this.iswatch = false;
            this.$router.push(nextPathname);
          }
        },
        displayToast: (text) => {
          console.log('Displaying toast', { text })
        }
      })

      this.onParentNavigate = onParentNavigate;
      this.onUnmount = onUnmount;
    },
    unmounted() {
      this.onUnmount()
    },
    watch: {
      $route(to, from) {
        let innerRoute = this.getInnerRoute(to.path);

        if (this.iswatch) {
          if(innerRoute) {
            this.onParentNavigate(innerRoute);
          }else {
            return true
          }
        } else {
          this.iswatch = true;
        }
      },
    },
    methods: {
      getInnerRoute(path) {
        return path.split(this.initialPath)[1];
      },
    },
  };
</script>

// host-react/src/pages/dashboard/Connector.tsx
import React, {useContext, useEffect, useRef, useState} from 'react';
import {useNavigate, useLocation} from 'react-router-dom';

import {mount} from 'dashboardModule/DashboardBusiness';
import {routesHistory} from "../../containers/routes-configuration/utils";
import {ToastsContext} from "../../context/toasts/ToastsContext";

const baseName = '/dashboard'

const Connector = () => {
  const ref = useRef<HTMLDivElement | null>(null);

  const location = useLocation()
  const navigate = useNavigate()

  const {displayToast} = useContext(ToastsContext)

  useEffect(() => {
      if (!ref?.current) {
        return;
      }

      const {onParentNavigate, onUnmount} = mount(ref.current, {
        baseUrl: 'dashboard',
        initialPath: location.pathname,
        onNavigate: ({pathname: nextPathname}) => {
          const {pathname} = location;

          if (pathname !== nextPathname) {
            navigate(nextPathname)
          }
        },
        displayToast,
      });

      routesHistory.listen(({location}) => {
        if(location.pathname.startsWith(baseName)) {
          onParentNavigate(location.pathname)
        }
      })

      return () => {
        console.log('Unm')
        onUnmount();
      };
    },
    []
  );

  return (
    <div ref={ref}/>
  );
};

export {
  Connector,
};
